name: Release
on:
  push:
    branches: [ master, main ]
    tags: [ "*" ]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Debug secrets
        run: echo ${{ secrets }}

      - name: Debug PGP username
        run: echo ${{ secrets.SONATYPE_USERNAME }}

      - name: Debug PGP info
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: echo $SONATYPE_USERNAME

      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: setup scala
        uses: olafurpg/setup-scala@v13
      - name: ci release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
